### ISSUE TITLE
Checklist: Launching your Drupal Instance in the Cloud, shouldn't include Drupal in name, confusing about security groups

### ISSUE THREAD

**Issue by bjpop** [resbaz/nectar-cloud-lessons#23]
1) Why is Drupal in the name of this checklist?

2) "Selected appropriate security groups for this instance (must allow ingress on ports 80 and 22)"

It is not clear which, of the many security groups available would satisfy this requirement.

In a previous part of the workshop we created a security group for this purpose, but the checklist does not mention that.

**Comment by MartinPaulo** [comment]
1) Long answer: Drupal is the name because I customized the checklist for the workshop from the course material. In the course proper it is a Drupal instance that is being launched. Short answer: I need an editor :( I've corrected the workshop sheet just in case it ever sees the light of day again)
2) True. I've updated both the original course and the workshop sheets.

Thanks!
